
  const products = [
    {
      "id": 1,
      "category": "beauty",
      "discountPercentage": 12.91,
      "price": 9.99,
      "rating": 4.69,
      "stock": 94,
      "brand": "Essence",
      "sku": "BEA-ESS-ESS-001",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp"
    },
    {
      "id": 2,
      "category": "beauty",
      "discountPercentage": 17.8,
      "price": 19.99,
      "rating": 4.44,
      "stock": 34,
      "brand": "Glamour Beauty",
      "sku": "BEA-GLA-GLA-002",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp"
    },
    {
      "id": 3,
      "category": "beauty",
      "discountPercentage": 10.23,
      "price": 14.99,
      "rating": 4.09,
      "stock": 36,
      "brand": "Velvet Touch",
      "sku": "BEA-VEL-VEL-003",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp"
    },
    {
      "id": 4,
      "category": "beauty",
      "discountPercentage": 15.66,
      "price": 12.99,
      "rating": 4.82,
      "stock": 123,
      "brand": "Chic Cosmetics",
      "sku": "BEA-CHI-CHI-004",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp"
    },
    {
      "id": 5,
      "category": "beauty",
      "discountPercentage": 11.4,
      "price": 8.99,
      "rating": 4.36,
      "stock": 47,
      "brand": "Nail Couture",
      "sku": "BEA-NAI-NAI-005",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp"
    },
    {
      "id": 6,
      "category": "fragrances",
      "discountPercentage": 10.99,
      "price": 129.99,
      "rating": 4.36,
      "stock": 63,
      "brand": "Calvin Klein",
      "sku": "FRA-CAL-CAL-006",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp"
    },
    {
      "id": 7,
      "category": "fragrances",
      "discountPercentage": 8.4,
      "price": 89.99,
      "rating": 4.44,
      "stock": 17,
      "brand": "Chanel",
      "sku": "FRA-CHA-CHA-007",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp"
    },
    {
      "id": 8,
      "category": "fragrances",
      "discountPercentage": 15.6,
      "price": 79.99,
      "rating": 4.26,
      "stock": 68,
      "brand": "Dior",
      "sku": "FRA-DIO-DIO-008",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"
    },
    {
      "id": 9,
      "category": "fragrances",
      "discountPercentage": 13.31,
      "price": 69.99,
      "rating": 4.19,
      "stock": 51,
      "brand": "Dolce & Gabbana",
      "sku": "FRA-DOL-DOL-009",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/fragrances/dolce-gabbana-light-blue/thumbnail.webp"
    },
    {
      "id": 10,
      "category": "fragrances",
      "discountPercentage": 14.39,
      "price": 79.99,
      "rating": 2.74,
      "stock": 91,
      "brand": "Gucci",
      "sku": "FRA-GUC-GUC-010",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp"
    },
    {
      "id": 11,
      "category": "furniture",
      "discountPercentage": 8.57,
      "price": 1899.99,
      "rating": 4.77,
      "stock": 88,
      "brand": "Annibale Colombo",
      "sku": "FUR-ANN-ANN-011",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp"
    },
    {
      "id": 12,
      "category": "furniture",
      "discountPercentage": 14.4,
      "price": 2499.99,
      "rating": 3.92,
      "stock": 60,
      "brand": "Annibale Colombo",
      "sku": "FUR-ANN-ANN-012",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp"
    },
    {
      "id": 13,
      "category": "furniture",
      "discountPercentage": 19.09,
      "price": 299.99,
      "rating": 2.87,
      "stock": 64,
      "brand": "Furniture Co.",
      "sku": "FUR-FUR-BED-013",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp"
    },
    {
      "id": 14,
      "category": "furniture",
      "discountPercentage": 2.01,
      "price": 499.99,
      "rating": 4.88,
      "stock": 26,
      "brand": "Knoll",
      "sku": "FUR-KNO-KNO-014",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp"
    },
    {
      "id": 15,
      "category": "furniture",
      "discountPercentage": 8.8,
      "price": 799.99,
      "rating": 3.59,
      "stock": 7,
      "brand": "Bath Trends",
      "sku": "FUR-BAT-WOO-015",
      "availabilityStatus": "Low Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/thumbnail.webp"
    },
    {
      "id": 16,
      "category": "groceries",
      "discountPercentage": 12.62,
      "price": 1.99,
      "rating": 4.19,
      "stock": 8,
      "brand": null,
      "sku": "GRO-BRD-APP-016",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/apple/thumbnail.webp"
    },
    {
      "id": 17,
      "category": "groceries",
      "discountPercentage": 9.61,
      "price": 12.99,
      "rating": 4.47,
      "stock": 86,
      "brand": null,
      "sku": "GRO-BRD-BEE-017",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/beef-steak/thumbnail.webp"
    },
    {
      "id": 18,
      "category": "groceries",
      "discountPercentage": 9.58,
      "price": 8.99,
      "rating": 3.13,
      "stock": 46,
      "brand": null,
      "sku": "GRO-BRD-FOO-018",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp"
    },
    {
      "id": 19,
      "category": "groceries",
      "discountPercentage": 13.7,
      "price": 9.99,
      "rating": 3.19,
      "stock": 97,
      "brand": null,
      "sku": "GRO-BRD-CHI-019",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/chicken-meat/thumbnail.webp"
    },
    {
      "id": 20,
      "category": "groceries",
      "discountPercentage": 9.33,
      "price": 4.99,
      "rating": 4.8,
      "stock": 10,
      "brand": null,
      "sku": "GRO-BRD-COO-020",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp"
    },
    {
      "id": 21,
      "category": "groceries",
      "discountPercentage": 0.16,
      "price": 1.49,
      "rating": 4.07,
      "stock": 84,
      "brand": null,
      "sku": "GRO-BRD-CUC-021",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/cucumber/thumbnail.webp"
    },

    /* ---- ids 10–21 already shared earlier ---- */

    {
      "id": 22,
      "category": "groceries",
      "discountPercentage": 10.27,
      "price": 10.99,
      "rating": 4.55,
      "stock": 71,
      "brand": null,
      "sku": "GRO-BRD-FOO-022",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/dog-food/thumbnail.webp"
    },
    {
      "id": 23,
      "category": "groceries",
      "discountPercentage": 11.05,
      "price": 2.99,
      "rating": 2.53,
      "stock": 9,
      "brand": null,
      "sku": "GRO-BRD-EGG-023",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp"
    },
    {
      "id": 24,
      "category": "groceries",
      "discountPercentage": 4.23,
      "price": 14.99,
      "rating": 3.78,
      "stock": 74,
      "brand": null,
      "sku": "GRO-BRD-FIS-024",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp"
    },
    {
      "id": 25,
      "category": "groceries",
      "discountPercentage": 0.16,
      "price": 1.29,
      "rating": 3.25,
      "stock": 33,
      "brand": null,
      "sku": "GRO-BRD-GRE-025",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp"
    },
    {
      "id": 26,
      "category": "groceries",
      "discountPercentage": 1,
      "price": 0.99,
      "rating": 3.66,
      "stock": 3,
      "brand": null,
      "sku": "GRO-BRD-GRE-026",
      "availabilityStatus": "Low Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/thumbnail.webp"
    },
    {
      "id": 27,
      "category": "groceries",
      "discountPercentage": 14.4,
      "price": 6.99,
      "rating": 3.97,
      "stock": 34,
      "brand": null,
      "sku": "GRO-BRD-HON-027",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/honey-jar/thumbnail.webp"
    },
    {
      "id": 28,
      "category": "groceries",
      "discountPercentage": 8.69,
      "price": 5.49,
      "rating": 3.39,
      "stock": 27,
      "brand": null,
      "sku": "GRO-BRD-CRE-028",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/ice-cream/thumbnail.webp"
    },
    {
      "id": 29,
      "category": "groceries",
      "discountPercentage": 12.06,
      "price": 3.99,
      "rating": 3.94,
      "stock": 50,
      "brand": null,
      "sku": "GRO-BRD-JUI-029",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/juice/thumbnail.webp"
    },
    {
      "id": 30,
      "category": "groceries",
      "discountPercentage": 15.22,
      "price": 2.49,
      "rating": 4.93,
      "stock": 99,
      "brand": null,
      "sku": "GRO-BRD-KIW-030",
      "availabilityStatus": "In Stock",
      "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/kiwi/thumbnail.webp"
    },
    {
  id: 31,
  category: "groceries",
  discountPercentage: 7.12,
  price: 1.99,
  rating: 4.12,
  stock: 40,
  brand: null,
  sku: "GRO-BRD-LEM-031",
  availabilityStatus: "In Stock",
  thumbnail: "https://cdn.dummyjson.com/product-images/groceries/lemon/thumbnail.webp"
},
{
  id: 32,
  category: "groceries",
  discountPercentage: 6.8,
  price: 2.29,
  rating: 3.88,
  stock: 28,
  brand: null,
  sku: "GRO-BRD-MAN-032",
  availabilityStatus: "In Stock",
  thumbnail: "https://cdn.dummyjson.com/product-images/groceries/mango/thumbnail.webp"
},
{
  id: 33,
  category: "groceries",
  discountPercentage: 9.45,
  price: 1.89,
  rating: 4.01,
  stock: 62,
  brand: null,
  sku: "GRO-BRD-ONI-033",
  availabilityStatus: "In Stock",
  thumbnail: "https://cdn.dummyjson.com/product-images/groceries/onion/thumbnail.webp"
},
{
  id: 34,
  category: "groceries",
  discountPercentage: 5.22,
  price: 3.49,
  rating: 4.22,
  stock: 19,
  brand: null,
  sku: "GRO-BRD-ORA-034",
  availabilityStatus: "Low Stock",
  thumbnail: "https://cdn.dummyjson.com/product-images/groceries/orange/thumbnail.webp"
},
{
  id: 35,
  category: "groceries",
  discountPercentage: 11.9,
  price: 4.99,
  rating: 3.75,
  stock: 54,
  brand: null,
  sku: "GRO-BRD-PAS-035",
  availabilityStatus: "In Stock",
  thumbnail: "https://cdn.dummyjson.com/product-images/groceries/pasta/thumbnail.webp"
},
{
  id: 36,
  category: "groceries",
  discountPercentage: 3.4,
  price: 2.19,
  rating: 3.61,
  stock: 14,
  brand: null,
  sku: "GRO-BRD-PEA-036",
  availabilityStatus: "Low Stock",
  thumbnail: "https://cdn.dummyjson.com/product-images/groceries/peas/thumbnail.webp"
},
{
  id: 37,
  category: "groceries",
  discountPercentage: 8.77,
  price: 1.59,
  rating: 4.48,
  stock: 73,
  brand: null,
  sku: "GRO-BRD-POT-037",
  availabilityStatus: "In Stock",
  thumbnail: "https://cdn.dummyjson.com/product-images/groceries/potato/thumbnail.webp"
},
{
  id: 38,
  category: "groceries",
  discountPercentage: 6.19,
  price: 3.79,
  rating: 3.29,
  stock: 21,
  brand: null,
  sku: "GRO-BRD-RIC-038",
  availabilityStatus: "Low Stock",
  thumbnail: "https://cdn.dummyjson.com/product-images/groceries/rice/thumbnail.webp"
},
{
  id: 39,
  category: "groceries",
  discountPercentage: 4.88,
  price: 2.69,
  rating: 4.11,
  stock: 65,
  brand: null,
  sku: "GRO-BRD-TOM-039",
  availabilityStatus: "In Stock",
  thumbnail: "https://cdn.dummyjson.com/product-images/groceries/tomato/thumbnail.webp"
},
{
  id: 40,
  category: "groceries",
  discountPercentage: 9.02,
  price: 5.99,
  rating: 4.63,
  stock: 38,
  brand: null,
  sku: "GRO-BRD-WHE-040",
  availabilityStatus: "In Stock",
  thumbnail: "https://cdn.dummyjson.com/product-images/groceries/wheat/thumbnail.webp"
},
  {
    "id": 53,
    "category": "kitchen-accessories",
    "discountPercentage": 8.03,
    "price": 12.99,
    "rating": 3.7,
    "stock": 14,
    "brand": null,
    "sku": "KIT-BRD-CHO-053",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/chopping-board/thumbnail.webp"
  },
  {
    "id": 54,
    "category": "kitchen-accessories",
    "discountPercentage": 12.1,
    "price": 8.99,
    "rating": 4.63,
    "stock": 22,
    "brand": null,
    "sku": "KIT-BRD-CIT-054",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/citrus-squeezer-yellow/thumbnail.webp"
  },
  {
    "id": 55,
    "category": "kitchen-accessories",
    "discountPercentage": 14.76,
    "price": 6.99,
    "rating": 3.09,
    "stock": 40,
    "brand": null,
    "sku": "KIT-BRD-SLI-055",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/egg-slicer/thumbnail.webp"
  },
  {
    "id": 56,
    "category": "kitchen-accessories",
    "discountPercentage": 14.04,
    "price": 49.99,
    "rating": 4.11,
    "stock": 21,
    "brand": null,
    "sku": "KIT-BRD-ELE-056",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/electric-stove/thumbnail.webp"
  },
  {
    "id": 57,
    "category": "kitchen-accessories",
    "discountPercentage": 3.5,
    "price": 9.99,
    "rating": 3.04,
    "stock": 85,
    "brand": null,
    "sku": "KIT-BRD-FIN-057",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/fine-mesh-strainer/thumbnail.webp"
  },
  {
    "id": 58,
    "category": "kitchen-accessories",
    "discountPercentage": 8.07,
    "price": 3.99,
    "rating": 3.11,
    "stock": 7,
    "brand": null,
    "sku": "KIT-BRD-FOR-058",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/fork/thumbnail.webp"
  },
  {
    "id": 59,
    "category": "kitchen-accessories",
    "discountPercentage": 7.92,
    "price": 4.99,
    "rating": 4.02,
    "stock": 46,
    "brand": null,
    "sku": "KIT-BRD-GLA-059",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/glass/thumbnail.webp"
  },
  {
    "id": 60,
    "category": "kitchen-accessories",
    "discountPercentage": 3.56,
    "price": 10.99,
    "rating": 3.21,
    "stock": 84,
    "brand": null,
    "sku": "KIT-BRD-GRA-060",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/grater-black/thumbnail.webp"
  },
  {
    "id": 61,
    "category": "kitchen-accessories",
    "discountPercentage": 17.02,
    "price": 34.99,
    "rating": 3.86,
    "stock": 84,
    "brand": null,
    "sku": "KIT-BRD-HAN-061",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/hand-blender/thumbnail.webp"
  },
  {
    "id": 62,
    "category": "kitchen-accessories",
    "discountPercentage": 0.63,
    "price": 5.99,
    "rating": 4.71,
    "stock": 13,
    "brand": null,
    "sku": "KIT-BRD-CUB-062",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/ice-cube-tray/thumbnail.webp"
  },
  {
    "id": 63,
    "category": "kitchen-accessories",
    "discountPercentage": 18.91,
    "price": 7.99,
    "rating": 3.09,
    "stock": 68,
    "brand": null,
    "sku": "KIT-BRD-KIT-063",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/kitchen-sieve/thumbnail.webp"
  },
  {
    "id": 64,
    "category": "kitchen-accessories",
    "discountPercentage": 18.86,
    "price": 14.99,
    "rating": 3.26,
    "stock": 7,
    "brand": null,
    "sku": "KIT-BRD-KNI-064",
    "availabilityStatus": "Low Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/knife/thumbnail.webp"
  },
  {
    "id": 65,
    "category": "kitchen-accessories",
    "discountPercentage": 10.34,
    "price": 12.99,
    "rating": 4.93,
    "stock": 94,
    "brand": null,
    "sku": "KIT-BRD-LUN-065",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/lunch-box/thumbnail.webp"
  },
  {
    "id": 66,
    "category": "kitchen-accessories",
    "discountPercentage": 12.13,
    "price": 89.99,
    "rating": 4.82,
    "stock": 59,
    "brand": null,
    "sku": "KIT-BRD-MIC-066",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/microwave-oven/thumbnail.webp"
  },
  {
    "id": 67,
    "category": "kitchen-accessories",
    "discountPercentage": 9.25,
    "price": 15.99,
    "rating": 2.64,
    "stock": 88,
    "brand": null,
    "sku": "KIT-BRD-TRE-067",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/mug-tree-stand/thumbnail.webp"
  },
  {
    "id": 68,
    "category": "kitchen-accessories",
    "discountPercentage": 3,
    "price": 24.99,
    "rating": 2.79,
    "stock": 90,
    "brand": null,
    "sku": "KIT-BRD-PRD-068",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/pan/thumbnail.webp"
  },
  {
    "id": 69,
    "category": "kitchen-accessories",
    "discountPercentage": 7.31,
    "price": 3.99,
    "rating": 3.65,
    "stock": 66,
    "brand": null,
    "sku": "KIT-BRD-PLA-069",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/plate/thumbnail.webp"
  },
  {
    "id": 70,
    "category": "kitchen-accessories",
    "discountPercentage": 14.52,
    "price": 6.99,
    "rating": 4.42,
    "stock": 82,
    "brand": null,
    "sku": "KIT-BRD-TON-070",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/red-tongs/thumbnail.webp"
  },
  {
    "id": 71,
    "category": "kitchen-accessories",
    "discountPercentage": 5.7,
    "price": 39.99,
    "rating": 3.22,
    "stock": 40,
    "brand": null,
    "sku": "KIT-BRD-SIL-071",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/silver-pot-with-glass-cap/thumbnail.webp"
  },
  {
    "id": 72,
    "category": "kitchen-accessories",
    "discountPercentage": 13.35,
    "price": 8.99,
    "rating": 3.4,
    "stock": 88,
    "brand": null,
    "sku": "KIT-BRD-SLO-072",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/slotted-turner/thumbnail.webp"
  },
  {
    "id": 73,
    "category": "kitchen-accessories",
    "discountPercentage": 12.09,
    "price": 19.99,
    "rating": 4.87,
    "stock": 79,
    "brand": null,
    "sku": "KIT-BRD-SPI-073",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/spice-rack/thumbnail.webp"
  },
  {
    "id": 74,
    "category": "kitchen-accessories",
    "discountPercentage": 15.5,
    "price": 11.99,
    "rating": 3.9,
    "stock": 55,
    "brand": null,
    "sku": "KIT-BRD-STR-074",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/strainer/thumbnail.webp"
  },
  {
    "id": 75,
    "category": "kitchen-accessories",
    "discountPercentage": 8.9,
    "price": 7.49,
    "rating": 4.1,
    "stock": 60,
    "brand": null,
    "sku": "KIT-BRD-SPO-075",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/spoon/thumbnail.webp"
  },
  {
    "id": 76,
    "category": "kitchen-accessories",
    "discountPercentage": 10.0,
    "price": 14.99,
    "rating": 4.5,
    "stock": 45,
    "brand": null,
    "sku": "KIT-BRD-MIX-076",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/mixing-bowl/thumbnail.webp"
  },
  {
    "id": 77,
    "category": "kitchen-accessories",
    "discountPercentage": 6.5,
    "price": 9.99,
    "rating": 3.75,
    "stock": 30,
    "brand": null,
    "sku": "KIT-BRD-KNE-077",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/kneading-bowl/thumbnail.webp"
  },
  {
    "id": 78,
    "category": "kitchen-accessories",
    "discountPercentage": 7.2,
    "price": 5.99,
    "rating": 3.85,
    "stock": 25,
    "brand": null,
    "sku": "KIT-BRD-CLN-078",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/cleaning-brush/thumbnail.webp"
  },
  {
    "id": 79,
    "category": "kitchen-accessories",
    "discountPercentage": 12.3,
    "price": 8.49,
    "rating": 4.2,
    "stock": 35,
    "brand": null,
    "sku": "KIT-BRD-MAT-079",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/mat/thumbnail.webp"
  },
  {
    "id": 80,
    "category": "kitchen-accessories",
    "discountPercentage": 9.8,
    "price": 6.99,
    "rating": 3.95,
    "stock": 40,
    "brand": null,
    "sku": "KIT-BRD-CUP-080",
    "availabilityStatus": "In Stock",
    "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/cup/thumbnail.webp"
  },
  ]


 
export default products